apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: {{ .Values.istio.controlPlaneNamespace }}
spec:
  # needs to be hard coded due to service mesh only supporting mounting of secrets by volume and not by kube api
  secretName: istio-ingressgateway-certs
  commonName: {{ index .Values.ingress.hosts 0 }}
  dnsNames:
  {{- range .Values.ingress.hosts }}
  - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ .Values.ingress.issuer.name }}
    kind: {{ .Values.ingress.issuer.kind }}